local input = "JppMDcJPcQbqGqFb\nZStgnHtsSjGBhqFbBmsm\ndjzzwgHHggdnfwjtMPDPMGpPlNfpLDll\ndRCtwtlCSttPtlNPNtgvPrDqmBsjGSpjBBsJsqqmrp\nZhWnZhzMMfnWWTDzBrmsmjsBccJB\nTFQMrZrMfZrLZZnLQdlvNdCgdHPlCllHNF\nPVddPnZWDDPqmHZzqVPzqdHdMRMJjQtvmvjvtTQQtlRtbbQl\nfsNswFpChpNwfgtMvCbjTRJBbtRj\nSFgfSMShLcsLgNMFhpwShFFZPHqZGZPqHdzPZHZcdzDDqd\ndHffzCqSfJCCzCPvdcpzRrBDDBSBBBMtthDDrFMT\nbVsZbsrgbWshBTFtDTtZTD\nslWGNbNWgWwnmNnwgnlGjdJJdPHcvcrcHjqPzdqPvp\nvBFBzGvGBvjFpGWcvCCvBvGPPhZbgLhMnhrPgFgPFgLLPF\ndVlslfdJNVJJmQQwdNRNwLZZZrrqhbPbZndpdgMhLP\nHJRHJpNJlVmftHfNQNRsHmmGCtGWjGDDTvCzcjWDStvcvT\ncVQzCCCpVVjgHsNwwFRqSRSRRtNH\nPWfhfPhbWWdWllPDdTvdbnvhLJLLMJFTSNwJtMRwJLqJJNMq\nDnfblllPbDrbWmbdPFdvlhdgQzzZZzQgcpcsZGcGQQgcpr\nhdFnnrdLnJRrZMzVlMbrwZvz\nTgfjGCcfsqfqqBfRMPDVvVVvTZRPbP\nqQqffcGStBSCQcsqCCBRjGqWhHFptFdnhNLmhnLWmphLLt\nWHPqWhLWHBMqddCdtDRwStDSwgnw\nrfCfZTmvpvvpFVfFrbvTbvcgtwgtStntggwbSJttgJtwgw\nfpQFsmfFmfZcrFCMhWNQWLCzhhCM\nzdqqJHDWwqNNZjQSmtdjpmfnjj\nGFBcPfBLPThcTcLRbpTQQjpTQrjSnQjlvn\nMFVLcsPVbPcRGfVPFRgDzJsHZNDCZNCNZsHg\nWQdMhlmQMwfZlQdgdHfddvtzmbJbcsctbBJqqcvqzB\nrSTrDDCSSGRCnnSGwwzJsbBvJsCCttccsvsz\nVnFwDrNwPwVSDrLgjfZZdMQFMWgljQ\nrJNjBLNQjvLQjFFLQJCFTvGWlRRgfGWDWlCDzlGnRRWG\ntMMhShhwhbgplflwDlnnnzDH\nZcSZVMSqshhQBQqQvqQgjJ\nbtTtWGbvtcvHHccdNRhHdl\nTDzqLPSqBzqVSldPddHhhNNlRQ\njBLDqDgZZBzJJmsbWjppmmpTWw\nLLDTRRfTwZRGZfDCRTwRsVHsVFBVZVlmVFBFlFJl\nQjWpQrzQcbhfMqrVVHVPFslFVpVmHH\nhqhzqMfNvjvMMzhdRDdCwGDSSdnvRn\njmMdNCLjLmJPtHtSHhSVVJ\npDBqgBgCvbfGBBbCGHZhtQZtPHVSVHPV\npBnWgBpzWzBbWDWvzwpgCvqcmLNTrdLmmrnRLTrmrTdmLd\ndRWWtRGBDPQctQDZ\nCMfnCfFMmTTFVCmfmTLvsnMPZjccHRcPrRPsZQQZPQDRrQ\nfLCffmRTCvRnmTllzVvpdpphNJggpGbJJJpdlh\ncfsfbbWqqZqDScbhGDPDjTPmpVtmmPjPntFD\ndCBBCRQCHNHLMQvrJJJBJLrGPMnjVtPjVMmnjPFmPmMpFn\nHvRGLddgHHvqhwzbWhcgcf\nDHmhhDDhbqrRhvbrHqhPbPvBwwWwTmMGTVwwBMGWVNNwVw\ngSzJjnnjsscfcsZcSfWwQGdMMcWTBcTTMTMw\nnsFCCFZsnSlCFBFflfflsztRPCqvvHPttRbHbhvPrrRr\nSGNRLzpNpgNSNNlWFNwzqJfHfJHBtBdJhBJrHd\nbQnjPTnjVdZtPPrfLP\nTTnTccLnjGFcDNggFl\nlBJmNzJlzmmQBlzgVVjLWRDfLjRsRLWWRS\nvTMvTvtrfdhrrrPTdZwTTwtDqSSnWFWDFMMsRssjjsRqWD\nZpbvHbZddtbrdrdhcBmmpGQfBQgJNcmz\nqsmhTmTVcDdcffhPhPvvzFhF\nBNNlJbjWBWjtRtNljbmBBCpFzPlFPgpPfwFnlffnlPgg\nJtBmmrrrRbDSrVqDqVSD\nVmSgpSLgJjVDMrFrmMlfFmsG\nbZWhZbzWcCwTWPRCwwwSPQzwMHnflHnGsMGnTrsflGMnlfTF\nCqWhWqWCCWRRZQcLqDLpVDDLNStpgD\nJwzTVzzcLzVJVVlJpVTwzGcrWhFjqsBjCjQFjWcCCjCjBF\nMDSNQMtbSSnSbgbRDvnRNgvhmrqrjBCBtmCrCCWFqthhWm\nbgMfNSSNZTwZQddGJZ\njjPgbFjjStjjPcSbrbtpvNrGnGDvBnMGvNDNGG\nLwdZwsTdWTTmwDNCNppGBsnpBR\nmWmHwZWhTTJWHBdQQWBjcFczSgjlSftjbtQPzg\nfCBlrffzlCzcmfLDlfgRRnHScsHvRSQHMQvs\nLthpZqtpVThZhGJtqTFvHsVnvsvMsggjHQjgQH\nZWFWGTLTWBNCWfDfmD\nBpFqJrpcZZBDhDsNqMHhRG\nzwlzPdmzPLhwvhMgsHnN\nmPlWjlQfQjjllWtjQCWzCrBFJFTBcSNcJbbZfcZJSb\nFpzNFTThBDChnnzNBCBNDzWGndgWqbJWVGqmPbJqQgQm\nHQRctcvwgddVcJGd\nLwRMZLjQfSRjFNzFSrhNsThS\nWgRWVLWhFqgqgcgWHqLRWHVRbbbNwBmtBcNcwdwwBNwBzwBN\npSfssjDSrSvJpNJCztbJBtMNbt\nTzsvGGnjGPsPjSTpDrPfPDSHhWqLgZZVHVhZZZZVQQFLnZ\nsHjtPjQTtDbsfrrqWR\nZmccchvlvSvvZNMVNhvBLWRJJblWJWJlJfwHbwlL\nhMMBzSMppVSzSNNmNgHjPgGPFTCpTTgTgG\nrPQpCPPCQQZdcFhcZgzVJgwt\nvDBSHmvHSSMlDWWmljnHBvFwzzcrwhVSJwVFtzcJJghw\nbmmrsrsbsvNdCTdbPTdb\nNgzBnsBNnfjgNvvfvWbtShSSFSMLJMFjjbPh\nCCcRHdlQrQPLTJPLGP\nHrDlRcqcDJCCDJHlcplrDJDfgfzBWWNZfvsnNqWwngZWwW\nTggFVbjVTVzRwFFjjqBBqpzNztqcQqNNqN\nSnZPrWndmShSZSPsnSLsJhpMQpcJtNqBClltqctC\nmfWsGdnZZWmZmrLSfsrnmPggwtggRgGTVHvRwgFDjTGT\nwQMZFQwppbPHPbLQJsgQNJJmBnds\nqrSGvRRCvTzTDNnhNgmCgdBm\nqzRrcRlGjvvzlzrvjcGqSSzMHWwVdPMWFpFMHMHWlPWMVV\nBccsFzrBcsfpccccgFmQqlGNqCTLTlQnqgLlRG\nMZbVSMddddSPPtdHPVJPJdTllqLNLGGTNCCRhTnHTQHh\nDMwtbVZDZbSbpprcpccppwrq\nbSZTdNqFjjzjqQMQ\nWtRztLsWJpPLzrsMDlDQjMhVMC\npcgHRpHmWPJgLRzBJHBPPRBfvvfGNGvvFwfvSvfTmNNZfN\nRjvBljWTTWTlqmBvHjGptRgccZcbPtcttbpzbn\nVhDSDdJLJpSNNVVznPzzzSzcZFngZt\nLsMdQNVMHsBHjqps\nrSPSLTnSCClfSFCR\nMwtZgwNBzzTjzZMbbmjNtwmBcRvFqQllqtQRlFRVqRqVVcvq\nTsMhZsjNjBbTbBbwZLpDnHdDGdHWnpGHnh\nLfdssTFBjFHSwlhzCcZZgMMfMhZZ\nDmtDvrpmNStVvqpPczrZMMhZhhChCC\nvJtJpQWvNVDtJFbHlJSlBbSF\nPgvHLbcgRcGGHzRvgGgchBzsCZnmNZmZddrCrvdddZCZrF\nJQBMjlStJrQsZFrNCZ\nJSJTlqMtjptlplSSqJVDBqphwhhwHRPRggGbGzHbgzVRPH\npBsztsZdBsnWhntVnhtVTqTWNQlGGTGGFFlQFlTl\nfDvLSMcbDbfMrGqFqSGwSQPzqz\nzjcvLMMvffLjgggzfjjJCCLcdBtRphddBmmZBpCZZpZpmmhs\ngmmSDplcPHDfHDlbVNrtCtCCNqHvTn\nQGwJjzdPMzJhFLwnbvMqrTVCCMnvMv\nLQQZdGjGdJhFBFQGjLGBJzzsBSWcPflllcfmDmfBsmBWPs\nsMppbLDRMQbrTDTJjwcqnfnjwwnw\nCgmFgSPHPzHgdmJWZZFzCzZZcVnGGnttWtVVVnccfjVqwVff\nPhCChPSNgPgPJhPHhFZgsDNRspsvMNQLRvNDvpbD\npHnVnlRGVpfgpfgCpCTz\nLCNQPqZCqNSSZCStzPgTmztwPfzwzT\ndbSqhjhqQhNLQLFjLjGvFcRnCcsvRVvvsFnG\nQTdnDTDQbCnMdbqdwSmJBljFJZhttJZMSh\nHfNfLNzGLsgWBpGJthlZFBSB\nssRPHPfNsWHzZZvrvHfgLzNwnbbVVRwwRbVVcqDTddCVdD\nZhZBrJssjrNsbRtWpjwjlmlm\nqTfHzGTfTGqqLGMdCCRcmmRRZcbPMccWmcRw\ndVCZdDHdGHQhBVNJSsBhBF\nNsplbGDbblHcbCpDlDGDPlPpJjdrVjgrvHnghvVdJrJdvvdn\ntQFMZNWSmWFQRzQSwtzFmwFFJdVBghVrnBjVjBgrvVjMvrhJ\nFFRmFZZRzQRmFLQSZZWQWFCPCNGcTCpGpfGfLTpblpff\ndnhQHqQCnqWwNQCwCRRdJjjJVVPmVVJsJP\nLccFRDgfMgLFBJVlmVVmgjrPzZ\npvfGpRpSpTnTQbvbTv\nnwNlWwhWwNmJvQQdzdzZGMqDzn\nrcVscPfrLcfvjTFcQDqGdZqMzMSHZHjS\nLsfbbFcvVgRRblJRNR\nRmrrlmltcffhllfl\nDDZMMMFZVsFsWZDSHhPPfgQbPPnQgcHctf\nzGMGSBVDWCrvwjtBvm\nDCZHwdDwNNGNZDZCjjtpTHLvtlgLbRLttlTL\nBzPzBJffJJQgLlRgGztQ\nPJffcJhJfNNSwFhGZC\nblplfHbwZSfbcbwSbfVSHDHcNvdrvrWsCrvWVCRWnvNndtWW\nhQzBTQLLMBWBsnsnNC\nzMsgTjqTqPpZHbfp\nZLNNLtfZhRJQtpQhNRttZRqcGFcqGBzjrcqclGScFljjcj\nVnvVVPMWHwgJCMvwdcGFdFrGcwzGBG\nWHgPJJvWVTgnvgvTHmWCHmsNZRtNRDZpfZQffZZssR\nrZgMFMVVjGbVSqZbhftLRDmCGRCNDCtm\ncdddQzdWsWnQvzscnfRHmfnDNtLNChRmfH\nzplDQdDzwszlDsWdPcldzMFFrFrBFgpqVBZgSgZFrF\ngbzfbTvbJgbvzvTvJvJmzvjcBBQSfWDLCSBQQfLZWSCdBHHD\nGhnMhsGrMNPPwnwsRPNsFCZDWHZdWBWHdrZLdCHBBC\nPsnGsssGNsNRFsLGwMVNccJVmbjcjJblbzTVjlTz\nRfBqNfVmPLTTTVRZMMBWjlMvBgbbMs\nrHJzDwJdHzQgbMQlWMhd\nHtJrpCcHflLPFfpq\nSSGtmjQFStDbQbqGWJNnpZwgPsZjnJNNfZ\nRdClRMhlldHdlvdThNgwfJNRspNwJpwZcN\nCMBLgvvBLhrrBHTCVVLBQrWtbrDGmbtWGtzDQFGb\nZRRCqHpRdztLSqWz\nhRsGjMVccGshPVDVcBmfgFFzggFgfBmWWtSd\nPVjlGhcGJjGPsGMjjDVrMTpRnvRZlHnZNNQbHppTTC\nQjbjWWlndRbwwwQWQdtpTVVZtzRPhHDzThhP\nfFfLsvrLCrmvGlSfLSrlPHThDzTztHVtzDzGtTVh\nfvrgsfccFLLLSvfMCCSWBjdMqdqNWBdBQNnWld\npjGPvvbllvqGvGjwMbpbRmgSmSwtRtShgSSWWQmW\nDffTZLLzFFFTCRJMhWBzhmhgJt\nCVVZLLTTsZTFCnMffMTFHffLVpGpNqGjNbNPljqVPcGNGlcv\nrvJfztqQJqqrqHHwCzClTbBhDBBDrbSgphbVTrrV\nFFGdNWFLGWMmLDbpRwVbgRBp\ndmNGmZjMjQwtHCCw\nMSGbqbqMbbGDhSSGDhLNBPNcrDPPfzfczPfrnv\nrRwsrljslRgslwwgpssCjRtBNvnmPmBmccvmPnmzcP\nCjVjsssJQpTCrCCgHJLMSZbhMhWGZhHG\nJtBGBFGRVGVLLctRttthLFRBDQlDppljJwNQlpHHQqDHbHHN\nszSZTrzdzTSMdzsmsqqQqwdbgDNqgQNjlN\nSzmrlWPrlfPMsMZTPtCVCFRhhvhccLFPvL\nchmbsMDMMcBnGbZBzZGL\nJjjgJrJJggNgtrQSQBLjWBZlGnnB\nrFNrFtFCRNVrrsHmMDcsLqMhMF\nDLMwrBGgrBBDrcBcNBgWhpGhqVhhqSjqqqmjjp\nJfJCZCdtlbZlHHbjWVpPmHWb\nlTtZtnFQCztWFzJflZLcsrLFNDRNBcswcLMM\ntsVttVCBsCcCqPqwvtqNPQjWDDWjzQQWnpJQSrWJJN\nLMRdZvHGgMmZZGGLGLbhLhJpjWrSjndWJpSJrJppJnpj\nRhRgLMlmgMGMFGLlTtcBvwcfFCtVvfFT\nllBBmtncBglfqwsdwsjdbHwQHm\nzGRhPJvFzhvFvMDGFvGPwSWWQpdpHSwSjWjHsWMw\nJGFhDPrLTzhLhvFPzPjLjTzFlBqltnCqqBffcTgfnZfCfCnB\nQWQGNHQBffCNDMPdRTDLPVMN\nhrtlhtzZwJtwwgFgtlJthJJtZMqPVVpLmDVqRDmVPmMPVRTV\nSJSSnJwJlsFFvcHSBbfLQHGL\nzMNVzhNFsdNssmhlvtQvlttBlVGbTt\nwHpFwjHjLFHlwtncTQlnwn\nCCpjpqLCLqJggghqRmFsNRFmPszh\nCTjmprmNcnmCNVQbstnstvbnQv\njqqdGhHgPRdfRRQvfLQffz\nBGgqBhMdgqBHMDDqqMPwgdhSTJNjjmJWWCTCCmwTWZNpmZ\nLqSDFFmdqDBDbbBHWl\ndQcRpgwRQPngBWHbVWht\nvdQMJQCQQvrJNqrTNsSZSmZT\ncqrHcHHFNFPLLNPHLWnHHFHFjvlbZfWjSjBjZfSblhbBSbSf\nVdVTGwTzTwTpMJslvjfsbbZSvnBClj\nnJdGmmTpTTdmNQNNLPPmDFQL\nVcjpTTtpcbThJBTTcjBvSPJzJlvPlwfJrgrgvw\ndmshCNqnqdhmRsCsqCnrNgPPrPfzrNLfSwSgzl\nddQZdFnhsMttFTbDDD\nhLThMTSdfMzzLzTLsFTbwtDvtsFTnttF\npZlNllPWrPCQPQlWNqjrqrjsnfDFbbtbstwswtvDnwtwjt\npCNNQBCClQrplrfHQpQdSRMSVRhJzRchRhGHSh\nRZfVfRnTcPQWZcRVcRNSvljQsSSjNvvNqvss\npwbwgmqJhGlNvvzgMM\npthrhpmthmwhHHpLbbdrJmLWWRPTRZnCnPCPBnWTWTZq\nnzsJJsMjGMMsQFbnNmLnmCfb\nHlllPPTPlWTPDRRDRHcwwhrLLZfQmgmmQCFHvNZCgfggZQ\nlPcNTwNWddGsMSttdjzj\nbTbJZJDVFdqpBZTFTZJprdcsjjGszmjQszcjzDvsgccv\nHHLnhMNCCPhfhCLMlPlnvgGfctscSvtSjGjztQtm\nwWNQMPPMwlPHHPnnRLwWpJbrbbqbdppqJVJdZV\ngpgpNnnrhwBVWFqgjqqF\nZCTsdRbCGZpZzCSGbWmtMBmWtqBBqdjjmq\nLcsTSlplZrJNcQQPvH\nDJDpMcqJDcDddNcJPGcJGFfnfZZmZZfRQZRNmVQVnBNn\nWWThvSSHFshlSsHvgTHLlzBQfVWwmwnnfmRQWnQVRn\nvljlgHjhstHbLhjLjrbPqMGJcJFJCMPrdF\npJlPMpMBrrMcnrBBMMrvdhdgFvmcFdWtmdtftg\nbVVRmTRVTVVSVVVzZZqsggFHWTWtWffWFfWdtHdH\nRjLQDSzmVsjRRZSZQrCMJDPwlnJJnGGrPB\nGRgJtglPGlCrhQQrfW\nvSjvZvZHNBjZSvwjvmvNDqhhFqhHrMhrHpfWqQfhpW\nNBmwDSbZbvsNNBjmZfJzJgbVnGJbzVzPVRtL\nQQZVQCdlVmdZnWmJBrLwSJRdggwdJr\nDqHhPhcpvDqPFjhHjtFPssSJNfSBwBvffrgJwwJLBJbr\njpsHcptHsqtPttsjctpFhGlZwCMlWMmWGCWVQnTMVWmz\nzzvnHjHWSfnvzpnfSRHdgrrsmWmhVrrwwbTrTmsrwm\nNlLNGqqclqlZZCLCGGCPllJhhPJbrmpmrwVshFVsJbwr\nDMLDNCZQCGLQGDtQpGtMjRdfdSRSSBtjtBjfjgjS\nWBBJfjBQJjftGCbttVJptC\nsdlmTHsqNsqpRtGcbWdbnR\nsvNMhmWHNmvmvHZWTvBQDgSSjDFPSBSFPP\nmrlgqncgwHdqWWhRNtRttSvbRwwSvN\njZLCZVZzVcCTcpCDVSBBSbvvRFbfDBSDNS\nVPJVpQjTZLjVLJJQGZTZGcQVghsGlmhshlqnghqrdrgldhlW\nqwGDMqMFWbFbqbDwMgqgnjfnffffcTTjNnpTfBncZZ\nlSdclSltlzPsJlhNNfTQPTmQhpPh\nLtllsscLLLvvJlSzWGqwrDGqvbqMwMGb\nbnfvnnQsVTdHQDmdNN\nfwlttwrfSfLwdGZGmGND\nqlPrjjplfSpjSltfttBBsvgzgbgnggBqWVvC\nHHrBSmBqBHdHCFcQsc\nWqtMDDnMMZhMhcsQVM\nbqtbGDLLTTnRPwvGgBNmNrwvjm\nRwWzWFwBcdSdMgJW\nmrTjVQDQthQvjrvTmggFbbdgSJcJDFgSdg\nphhFtvjNvFvTTvmTHZzlGlzZRZLBlzRp\ncHlZmZmJSHZcTVGmvZVcGVHlNtbDNbtWFWdtlbCWbWtQDFdr\npwfwgRhngPjjtdWdNtFrdFwT\nRTgMpfhBcMJGHqcz\ndmCbpCLQVFmCRddCTFLCgZtWPNBhSNNwZWgWZvSwhN\nrDzGDjJHhhwzThBS\nrJrclsjjsJMJnJMLnbQQQFmRTqLVRT\nTgFTGPtrWHzgCJDz\nfQbfLwbbFbWjHJHWjd\nLvQvwVfQvQhLLLLsmMBfLfBhqchtGFSNSFNqrSqPcqSGttSN\nMsMmFgTVMMgMdFVMhdzWqCCBCWjWqBWqhzzL\nnHfZDlbvcrDpcpcfDJbNJqGLbCjBmjLzJC\nRnDZHwmmTwVMTsMS\nNpdpdnjNCRjBnHRPpBDnhSdSwFFLFdScFFWcFWLd\nstqMrMZtsQMJmMqvrtqMbstQVchPFWgFVVFVwfWJcSSWVSSV\nMQrZzbvMrrrZZtZmstMtMsDRRjPHCGTjBnzpnDHTCGjG\nClGGvDMGMNhNSmFVPbpgFgmFgZPb\nWhTTLWsBBWTcrPpggtQpsQFpVb\nfBRTqWLjTrzDNhMvCSGDzl\njbzjttVzpbWzWVbTtzWzVwPbPPcwDDccccFNFLMFsm\nrlghJZHmCHvHJvRLSNLhhhccNPwcMP\nQffmBZRBGtVTBdTG\nbDRqHwwRpNPnbppn\nFqrlQSQJSVsQrSCmpdPNpcNCcP\njFZjrssjBhrZVhJLLGHfMHfwtqRjMqRTvD\nSMMCTBzFfSRhTThCSMRSzzHnJgqGDHQgGVDnqrqnqqnqcQ\nljvjpWPbrWWtrbmDVDlmnDnqVmgJ\nbNjsNPrNPtswfZzfTSTBwhSM\nhNMNdssdMqdTQchqgNZzHtwmwGHHzmQZGHDH\nJrbJvJrvLrPjrPCVCjRBLPbzfRFZmzwHgFHmGHmwFwzFZR\nrpbrvVjPCBbCJrCSLSPsTlphNncMglcNTMWMql\nfGWGHbrllCCWWllFNPQSZvdPSvdZTffZ\ntqssVjJMJWzWVvSvWS\nqtwMwDWjnRRwssWjngwjjnhhDcCLhhCFHlcmcbCHFmDC\nrFTdFjdRDTTlDWCqvhwLhwZdLS\nQzfJfnfsbsJHMnNmHhVpCZwSQSWqSqVQhS\nnJnczsHzNMmBJnbnbNwnfzJfcDTltllRTgPlFlgPrTDjPRGl\nZLCGDvvJlvGChSPZWPSsZWdRRN\nrQccBwcccnHmQggnVLPLWpgVWPpWzSRs\nfmwTfTHnMBTfJDbfftJLvhlL"

function iterateByLine(s)
	if s:sub(-1)~="\n" then s=s.."\n" end
	return s:gmatch("(.-)\n")
end

function findCommonCharacters(first, second)
	local common = {}

	local v1 = {}
	local v2 = {}

	for i = 1, #first do
		v1[i] = first:sub(i, i)
	end

	for i = 1, #second do
		v2[i] = second:sub(i, i)
	end

	for k1,v1 in pairs(v1) do
		for k2,v2 in pairs(v2) do
			if v1 == v2 then
				common[#common + 1] = v1
			end
		end
	end

	return table.concat(common)

end

function getPriority(letter)
	if (letter == string.lower(letter)) then
		return string.byte(letter) - 96
	else
		return string.byte(string.lower(letter)) - 70

	end
end

local sum = 0

local lines = {}

for line in iterateByLine(input) do
	lines[#lines + 1] = line


	if (#lines == 3) then
		local common = findCommonCharacters(lines[1], lines[2])
		local badge = findCommonCharacters(common, lines[3]):sub(1, 1)
		local priority = getPriority(badge)

		print(badge, priority)

		sum = sum + priority
		lines = {}
	end


end

print("Sum: ", sum)


